"""add post_images table

Revision ID: 463dda3d16e4
Revises: 
Create Date: 2025-12-27 22:30:24.443466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463dda3d16e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_image')
    # ### end Alembic commands ###
